[flake8]
ignore="E203,W503,F632,E266,E731,E712,E741"
max-line-length=80

[tool.autopep8]
max_line_length = 80
ignore = "E501,W6"  # or ["E501", "W6"]
in-place = true
recursive = true
aggressive = 3

[tool.black]
line-length = 80
